/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FinanceManager;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ResourceManager;
import model.ResourceRequest;
import roles.FinanceManager;

/**
 *
 * @author DELL
 */
public class FinanceManagerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private ResourceManager resourceManager;
    private FinanceManager financeManager;
    private ResourceRequest resourceRequest;
    /**
     * Creates new form FinanceManagerJPanel
     */
    public FinanceManagerJPanel(JPanel userProcessContainer,ResourceManager resourceManager,FinanceManager financeManager,ResourceRequest resourceRequest) {
        initComponents();
        this.resourceManager=resourceManager;
        this.financeManager=financeManager;
        this.userProcessContainer=userProcessContainer;
        this.resourceRequest=resourceRequest;
        populatePendingRequestsTable();
        populateBudgetDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingresources = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTotalBudget = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAllocatedBudget = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finanace Manager  Work Area");

        tblPendingresources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "From", "Resource Type", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPendingresources);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Budget");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Fullfill Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTotalBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBudgetActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Allocated Budget");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pending Resource Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(txtTotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txtAllocatedBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(560, 560, 560))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtAllocatedBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int selectedRow = tblPendingresources.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a request to approve.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the correct request ID from the selected row
    String requestId = (String) tblPendingresources.getValueAt(selectedRow, 0); // Ensure the ID column is being fetched correctly
    double totalCost = (double) tblPendingresources.getValueAt(selectedRow, 4); // Total cost column

    // Approve the request
    boolean success = financeManager.approveRequest(requestId, totalCost);
    if (success) {
        JOptionPane.showMessageDialog(this, "Request approved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Move the approved resource to available resources
        resourceManager.moveApprovedRequestToResources(requestId);

        // Update the budget details in the UI
        populateBudgetDetails();

        // Update the pending requests table
        populatePendingRequestsTable();
    } else {
        JOptionPane.showMessageDialog(this, "Insufficient budget to approve the request.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBudgetActionPerformed
    private void populatePendingRequestsTable() {
     DefaultTableModel model = (DefaultTableModel) tblPendingresources.getModel();
    model.setRowCount(0); // Clear the table

    // Iterate through all requests in the resource manager
    for (ResourceRequest request : resourceManager.getAllRequests()) {
        // Only include requests with status "Pending" and created by "LogisticsManager"
        if ("Pending".equals(request.getStatus()) && "LogisticsManager".equals(request.getRequestedBy())) {
            model.addRow(new Object[]{
                request.getId(),
                request.getRequestedBy(), // From
                request.getResourceType(),
                request.getQuantityRequested(),
                request.getPrice(),
                request.getQuantityRequested() * request.getPrice() // Total cost
            });
        }
    }
}
    private void populateBudgetDetails() {
        DecimalFormat df = new DecimalFormat("#.00");
    txtTotalBudget.setText(df.format(financeManager.getBudget().getTotalBudget()));
    txtAllocatedBudget.setText(df.format(financeManager.getBudget().getRemainingBudget())); // Remaining Budget
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendingresources;
    private javax.swing.JTextField txtAllocatedBudget;
    private javax.swing.JTextField txtTotalBudget;
    // End of variables declaration//GEN-END:variables
}
