/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DisasterCoordinator;

import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Place;
import model.RescueResourceManager;
import model.ResourceRequest;
import model.SecurityResourceManager;
import model.WorkRequest;
import model.Zone;
import roles.DisasterCoordinator;

/**
 *
 * @author DELL
 */
public class DisasterCoordinatorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DisasterCoordinator disasterCoordinator;
    private RescueResourceManager rescueResourceManager;
    private SecurityResourceManager securityResourceManager;
    private Boolean disasterSet = false;

    public DisasterCoordinatorJPanel(JPanel userProcessContainer, DisasterCoordinator disasterCoordinator, String place, RescueResourceManager rescueResourceManager, SecurityResourceManager securityResourceManager) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.disasterCoordinator = disasterCoordinator;
        this.rescueResourceManager = rescueResourceManager;
        this.securityResourceManager = securityResourceManager;
        txtplace.setText(place);
        if (this.disasterCoordinator.getDisasters() != null && !this.disasterCoordinator.getDisasters().isEmpty()) {
            disasterName.setText(this.disasterCoordinator.getDisasters().get(0).getName());
            disasterDescription.setText(this.disasterCoordinator.getDisasters().get(0).getDescription());
            if (this.disasterCoordinator.getDisasterPriority(this.disasterCoordinator.getDisasters().get(0).getName()) != null) {
                this.textPriority.setText(this.disasterCoordinator.getDisasterPriority(this.disasterCoordinator.getDisasters().get(0).getName()));
            }
            //this.populateZoneTable(this.disasterCoordinator.getDisasters().get(0).getName());
        }
        populateRequestsTable();
        populateAvailableResourcesTable();
        populateRescueRequestsTable();
        populateRescueAvailableResourcesTable();
        // Add mouse listener for zone table
//        tblZonePriority.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                int selectedRow = tblZonePriority.getSelectedRow();
//                if (selectedRow >= 0) {
//                    // Fetch data from the selected row in the Zone Table
//                    String zoneName = (String) tblZonePriority.getValueAt(selectedRow, 0); // Zone Name
//                    String currentPriority = (String) tblZonePriority.getValueAt(selectedRow, 1); // Current Priority
//                    String managerName = (String) tblZonePriority.getValueAt(selectedRow, 2); // Zone Manager
//
//                    // Set the text fields with fetched data
//                    jTextField3.setText(zoneName); // Set Zone Name
//                    jTextField4.setText(currentPriority); // Set Current Priority
//                }
//            }
//        });

        // Add default priority options
        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"High", "Medium", "Low"}));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"High", "Medium", "Low"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        disasterName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        disasterDescription = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textPriority = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        lblplace = new javax.swing.JLabel();
        txtplace = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSecurityResouceType = new javax.swing.JTextField();
        txtSecurtyQuantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnrequestsecurityresource = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSecurityRequests = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecurityRequestsAvail = new javax.swing.JTable();
        btnsecurityviewrequests = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSecurityResourceUsageType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSecurityUsageQuantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnrescueviewrequests = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtRescueResourceUsageType = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRescueUsageQuantity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRescueResourceType = new javax.swing.JLabel();
        txtRescueResouceType = new javax.swing.JTextField();
        txtRescueQuantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnrequestrescueresource = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRescueRequests = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRescueRequestsAvail = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disaster Coordinator Work Area");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Disaster Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");

        disasterDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disasterDescriptionActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Initialize Emergency Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Current priority");

        textPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPriorityActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Set Prority");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblplace.setForeground(new java.awt.Color(255, 255, 255));
        lblplace.setText("Place");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resource Type");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity");

        btnrequestsecurityresource.setBackground(new java.awt.Color(0, 0, 0));
        btnrequestsecurityresource.setForeground(new java.awt.Color(255, 255, 255));
        btnrequestsecurityresource.setText("Request Resource");
        btnrequestsecurityresource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestsecurityresourceActionPerformed(evt);
            }
        });

        tblSecurityRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Resource type", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSecurityRequests);

        tblSecurityRequestsAvail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Resource Type", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblSecurityRequestsAvail);

        btnsecurityviewrequests.setBackground(new java.awt.Color(0, 0, 0));
        btnsecurityviewrequests.setForeground(new java.awt.Color(255, 255, 255));
        btnsecurityviewrequests.setText("Use Resorce");
        btnsecurityviewrequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecurityviewrequestsActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resource type");

        txtSecurityResourceUsageType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecurityResourceUsageTypeActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantity to use");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Security Resource");

        btnrescueviewrequests.setBackground(new java.awt.Color(0, 0, 0));
        btnrescueviewrequests.setForeground(new java.awt.Color(255, 255, 255));
        btnrescueviewrequests.setText("Use Resorce");
        btnrescueviewrequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrescueviewrequestsActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Resource type");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity to use");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rescue Resource");

        txtRescueResourceType.setForeground(new java.awt.Color(255, 255, 255));
        txtRescueResourceType.setText("Resource Type");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Quantity");

        btnrequestrescueresource.setBackground(new java.awt.Color(0, 0, 0));
        btnrequestrescueresource.setForeground(new java.awt.Color(255, 255, 255));
        btnrequestrescueresource.setText("Request Resource");
        btnrequestrescueresource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestrescueresourceActionPerformed(evt);
            }
        });

        tblRescueRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Resource type", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblRescueRequests);

        tblRescueRequestsAvail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Resource Type", "Quantity"
            }
        ));
        jScrollPane5.setViewportView(tblRescueRequestsAvail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblplace)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(disasterName)
                            .addComponent(txtplace, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(disasterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(textPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(765, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnrequestsecurityresource)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSecurityResouceType)
                                        .addComponent(txtSecurtyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSecurityResourceUsageType))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSecurityUsageQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnsecurityviewrequests, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRescueResourceType)
                                    .addComponent(jLabel18))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnrequestrescueresource)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRescueResouceType)
                                        .addComponent(txtRescueQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(12, 12, 12)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtRescueUsageQuantity)
                                                .addComponent(txtRescueResourceUsageType, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnrescueviewrequests, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(disasterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(disasterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblplace)
                    .addComponent(txtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(textPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSecurityResouceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSecurtyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnrequestsecurityresource)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtSecurityResourceUsageType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtSecurityUsageQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsecurityviewrequests))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRescueResourceType)
                            .addComponent(txtRescueResouceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtRescueQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnrequestrescueresource)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtRescueResourceUsageType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtRescueUsageQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnrescueviewrequests)))))
                .addContainerGap(423, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Create a new disaster request
        String disasterName = this.disasterName.getText().trim();
        String disasterDescription = this.disasterDescription.getText().trim();

        if (disasterName.isEmpty() || disasterDescription.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Disaster name and description cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Check for duplicate disasters
        if (!disasterCoordinator.disasterExists(disasterName)) {
            disasterCoordinator.initiateWorkRequest(String.valueOf(System.currentTimeMillis()), disasterName, disasterDescription, "Medium");
            JOptionPane.showMessageDialog(this, "Disaster created successfully!");
            disasterSet = true;
            if (this.disasterCoordinator.getDisasters() != null && !this.disasterCoordinator.getDisasters().isEmpty()) {
               // populateZoneTable(this.disasterCoordinator.getDisasters().get(0).getName());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Disaster already exists!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void disasterDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disasterDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disasterDescriptionActionPerformed

//    private void populateZoneTable(String disasterName) {
//        DefaultTableModel model = (DefaultTableModel) tblZonePriority.getModel();
//        model.setRowCount(0);
//
//        for (Zone zone : disasterCoordinator.getZonesByDisaster(disasterName)) {
//            model.addRow(new Object[]{
//                zone.getName(),
//                zone.getPriority(),
//                (zone.getManager() != null ? zone.getManager().getName() : "Not Assigned")
//            });
//        }
//    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

         if (this.disasterName.getText().isEmpty() || this.disasterDescription.getText().isEmpty() || !disasterSet) {
            JOptionPane.showMessageDialog(this, "Disaster name and description cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String disasterName = (String) this.disasterCoordinator.getDisasters().get(0).getName();
        String newPriority = (String) jComboBox2.getSelectedItem();

        this.textPriority.setText(newPriority);

        boolean success = disasterCoordinator.setDisasterPriority(disasterName, newPriority);
        if (success) {
            JOptionPane.showMessageDialog(this, "Disaster priority updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            //this.populateZoneTable(this.disasterCoordinator.getDisasters().get(0).getName());
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update priority.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPriorityActionPerformed

    private void populateRequestsTable() {
        DefaultTableModel model = (DefaultTableModel) tblSecurityRequests.getModel();
        model.setRowCount(0);
        for (ResourceRequest request : securityResourceManager.getRequestsByRole(disasterCoordinator.getRoleName())) {
            model.addRow(new Object[]{request.getId(), request.getResourceType(), request.getQuantityRequested(), request.getStatus()});
        }
    }

    private void populateAvailableResourcesTable() {
        DefaultTableModel model = (DefaultTableModel) tblSecurityRequestsAvail.getModel();
        model.setRowCount(0);
        for (String resourceType : securityResourceManager.listAvailableResources().keySet()) {
            model.addRow(new Object[]{resourceType, securityResourceManager.getAssignedQuantity(resourceType)});
        }
    }
    

    private void populateRescueRequestsTable() {
        DefaultTableModel model = (DefaultTableModel) tblRescueRequests.getModel();
        model.setRowCount(0);
        for (ResourceRequest request : rescueResourceManager.getRequestsByRole(disasterCoordinator.getRoleName())) {
            model.addRow(new Object[]{request.getId(), request.getResourceType(), request.getQuantityRequested(), request.getStatus()});
        }
    }

    private void populateRescueAvailableResourcesTable() {
        DefaultTableModel model = (DefaultTableModel) tblRescueRequestsAvail.getModel();
        model.setRowCount(0);
        for (String resourceType : rescueResourceManager.listAvailableResources().keySet()) {
            model.addRow(new Object[]{resourceType, rescueResourceManager.getAssignedQuantity(resourceType)});
        }
       
    }


    private void btnrequestsecurityresourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestsecurityresourceActionPerformed
        // TODO add your handling code here:
        String resourceType = txtSecurityResouceType.getText().trim();
        int quantity;
        try {
            quantity = Integer.parseInt(txtSecurtyQuantity.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (resourceType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Resource type cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Add the request to ResourceManager
        disasterCoordinator.requestResource(securityResourceManager, resourceType, quantity);

        // Update the Resource Requests table
        populateRequestsTable();

        // Notify the user and switch to LogisticsJPanel
        JOptionPane.showMessageDialog(this, "Resource request submitted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnrequestsecurityresourceActionPerformed

    private void btnsecurityviewrequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecurityviewrequestsActionPerformed
        // TODO add your handling code here:
        String resourceType = txtSecurityResourceUsageType.getText().trim();
        int quantity;
        try {
            quantity = Integer.parseInt(txtSecurityUsageQuantity.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (resourceType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Resource type cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = disasterCoordinator.useResource(securityResourceManager, resourceType, quantity);
        if (success) {
            JOptionPane.showMessageDialog(this, "Resource used successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the Available Resources table
            populateAvailableResourcesTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to use the resource. Insufficient quantity.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsecurityviewrequestsActionPerformed

    private void btnrescueviewrequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrescueviewrequestsActionPerformed
        String resourceType = txtRescueResourceUsageType.getText().trim();
        int quantity;
        try {
            quantity = Integer.parseInt(txtRescueUsageQuantity.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (resourceType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Resource type cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = disasterCoordinator.useRescueResource(rescueResourceManager, resourceType, quantity);
        if (success) {
            JOptionPane.showMessageDialog(this, "Resource used successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the Available Resources table
            populateRescueAvailableResourcesTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to use the resource. Insufficient quantity.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnrescueviewrequestsActionPerformed

    private void btnrequestrescueresourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestrescueresourceActionPerformed
        String resourceType = txtRescueResouceType.getText().trim();
        int quantity;
        try {
            quantity = Integer.parseInt(txtRescueQuantity.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (resourceType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Resource type cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Add the request to ResourceManager
        disasterCoordinator.requestRescueResource(rescueResourceManager, resourceType, quantity);

        // Update the Resource Requests table
        populateRescueRequestsTable();

        // Notify the user and switch to LogisticsJPanel
        JOptionPane.showMessageDialog(this, "Resource request submitted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnrequestrescueresourceActionPerformed

    private void txtSecurityResourceUsageTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecurityResourceUsageTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecurityResourceUsageTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrequestrescueresource;
    private javax.swing.JButton btnrequestsecurityresource;
    private javax.swing.JButton btnrescueviewrequests;
    private javax.swing.JButton btnsecurityviewrequests;
    private javax.swing.JTextField disasterDescription;
    private javax.swing.JTextField disasterName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblplace;
    private javax.swing.JTable tblRescueRequests;
    private javax.swing.JTable tblRescueRequestsAvail;
    private javax.swing.JTable tblSecurityRequests;
    private javax.swing.JTable tblSecurityRequestsAvail;
    private javax.swing.JTextField textPriority;
    private javax.swing.JTextField txtRescueQuantity;
    private javax.swing.JTextField txtRescueResouceType;
    private javax.swing.JLabel txtRescueResourceType;
    private javax.swing.JTextField txtRescueResourceUsageType;
    private javax.swing.JTextField txtRescueUsageQuantity;
    private javax.swing.JTextField txtSecurityResouceType;
    private javax.swing.JTextField txtSecurityResourceUsageType;
    private javax.swing.JTextField txtSecurityUsageQuantity;
    private javax.swing.JTextField txtSecurtyQuantity;
    private javax.swing.JTextField txtplace;
    // End of variables declaration//GEN-END:variables
}
