/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportManager;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.TransportVehicle;
import model.TransportVehicleDirectory;
import roles.TransportManager;

/**
 *
 * @author jrswa
 */
public class TransportManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransportManagerJPanel
     */
    private TransportVehicleDirectory vehicleDirectory;
    private JTable vehicleTable;
    private DefaultTableModel tableModel;
    private JPanel userProcessContainer;
    private TransportManager transportManager;
    public TransportManagerJPanel(JPanel userProcessContainer, TransportManager transportManager, TransportVehicleDirectory vehicleDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.transportManager= transportManager;
         this.vehicleDirectory = vehicleDirectory;
         tableModel = (DefaultTableModel) VehicleTbl.getModel();
         populateVehicleTable();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VehicleTypeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VehicleStatusTxt = new javax.swing.JTextField();
        RemoveBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VehicleTbl = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transport Manager  Work Area");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle Type: ");

        VehicleTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleTypeTxtActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Status:");

        VehicleStatusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleStatusTxtActionPerformed(evt);
            }
        });

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        VehicleTbl.setBackground(new java.awt.Color(0, 0, 0));
        VehicleTbl.setForeground(new java.awt.Color(255, 255, 255));
        VehicleTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vehicle ID", "Vehicle Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VehicleTbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 172, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VehicleTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VehicleStatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(RemoveBtn)
                        .addGap(51, 51, 51))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleStatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn))
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveBtn))
                .addContainerGap(369, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        // TODO add your handling code here:
                                
    int selectedRow = VehicleTbl.getSelectedRow();  // Use the correct JTable reference

    if (selectedRow >= 0) {
        // Get the vehicle ID from the selected row (assuming ID is in column 0)
        int vehicleID = (int) VehicleTbl.getValueAt(selectedRow, 0);

        // Remove vehicle from the directory
        boolean isRemoved = TransportVehicleDirectory.getInstance().removeTransportVehicleById(vehicleID);


        if (isRemoved) {
            populateVehicleTable();
            JOptionPane.showMessageDialog(this, "Vehicle removed successfully.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle not found or could not be removed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a vehicle to remove.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    private void populateVehicleTable() {
       // Clear existing rows from the table model
    tableModel.setRowCount(0);  

    // Add rows for all transport vehicles in the directory
    for (TransportVehicle vehicle : TransportVehicleDirectory.getInstance().getAllTransportVehicles()) {
        tableModel.addRow(new Object[]{
            vehicle.getId(),
            vehicle.getType(),
            vehicle.getStatus()
        });
    }
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        
        String vehicleType = VehicleTypeTxt.getText().trim();
        String vehicleStatus = VehicleStatusTxt.getText().trim();

        if (vehicleType.isEmpty() || vehicleStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all vehicle details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

      // Generate a new vehicle ID
        int newVehicleId = TransportVehicleDirectory.getInstance().getAllTransportVehicles().size() + 1;

        // Create a new vehicle instance
        TransportVehicle newVehicle = new TransportVehicle(newVehicleId, vehicleType, vehicleStatus);

        // Add the vehicle to the directory
        TransportVehicleDirectory.getInstance().addTransportVehicle(newVehicle);

        // Refresh the table to show the newly added vehicle
        populateVehicleTable();
        JOptionPane.showMessageDialog(this, "New vehicle added successfully by Transport Manager!", "Success", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_AddBtnActionPerformed

    private void VehicleTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleTypeTxtActionPerformed

    private void VehicleStatusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleStatusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleStatusTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JTextField VehicleStatusTxt;
    private javax.swing.JTable VehicleTbl;
    private javax.swing.JTextField VehicleTypeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
